name: WGLC Issue
description: Working Group Last Call Issue
labels: [wglc, triage]
body:
  - type: markdown
    attributes:
      value: |
        Working Group Last Call (WGLC) is your opportunity to raise issues against the following drafts:

        * [A Vocabulary For Expressing AI Usage Preferences](https://datatracker.ietf.org/doc/html/draft-ietf-aipref-attach-03)
        * [Associating AI Usage Preferences With Content](https://datatracker.ietf.org/doc/html/draft-ietf-aipref-attach-03)

        This is a consensus call on these documents in their whole form, which means that any matter not raised as an issue is presumed to have consensus.

        WGLC issues will be triaged and handled as follows:
        * Issues that are not within the scope of our charter will be closed without discussion.
        * Issues with the charter itself -- including whether the IETF should be doing this work -- will be closed without discussion.
        * Issues that are similar will be combined. If you see a similar existing issue and wish to add information, do so there (but note that "+1" responses and similar have little weight).
        * Issues that are deemed to be editorial will be reassigned to the editors and will be handled without further consideration by the working group.
        * Issues that have already been discussed have some presumption of consensus, but that will be confirmed as necessary. Genuinely new information is of greatest assistance when evaluating such issues.
        * Issues that have not yet been discussed will be evaluated on a case-by-case basis. Alternative approaches (e.g., "why didn't you do...") are presumed not to have consensus unless there is strong support for considering them.

        If you feel that your issue has been triaged incorrectly, please contact the chairs.

  - type: checkboxes
    attributes:
      label: "Confirmation"
      description: "Before raising a Working Group Last Call issue, please confirm that:"
      options:
        - label: I have reviewed our [existing WLGC issues](https://github.com/ietf-wg-aipref/drafts/issues?q=state%3Aopen%20label%3Awglc) and this issue is not present there.
          required: true
        - label: I have read and understand the [IETF NOTE WELL](https://www.ietf.org/about/note-well/).
          required: true

  - type: textarea
    attributes:
      label: "Issue Description"
      description: "Describe the nature of the issue. If relevant, please indicate the exact part of the specification where the issue is, using the section number."

  - type: textarea
    attributes:
      label: "Proposed Resolution"
      description: "Optional. If you have a proposal for how to resolve the issue, please describe it clearly."
