name: WG Issue
description: Working Group Issue
labels: [triage]
body:
  - type: markdown
    attributes:
      value: |
        Use this form to raise issues against the following drafts:

        * [A Vocabulary For Expressing AI Usage Preferences](https://datatracker.ietf.org/doc/html/draft-ietf-aipref-attach)
        * [Associating AI Usage Preferences With Content](https://datatracker.ietf.org/doc/html/draft-ietf-aipref-attach)

        Issues will be triaged by the chairs as follows:
        
        * Issues that are not within the scope of our charter will be closed without further discussion.
        * Issues with the charter itself -- including whether the IETF should be doing this work -- are not in scope of the WGLC.
        * Issues that are similar will be combined. If you see a similar existing issue and wish to add information, do so there (but note that simple "+1" responses and similar have little weight).
        * Issues that are deemed to be editorial will be reassigned to the editors and will be handled by them.

        If you feel that your issue has been triaged incorrectly, please contact the chairs.

  - type: checkboxes
    attributes:
      label: "Confirmation"
      description: "Before raising a Working Group issue, please confirm that:"
      options:
        - label: I have reviewed our [existing issues](https://github.com/ietf-wg-aipref/drafts/issues?q=state%3Aopen) and this issue is not present there.
          required: true
        - label: I have read and understand the [IETF NOTE WELL](https://www.ietf.org/about/note-well/).
          required: true

  - type: textarea
    attributes:
      label: "Issue Description"
      description: "Describe the nature of the issue. If relevant, please indicate the exact part of the specification where the issue is, using the section number."

  - type: textarea
    attributes:
      label: "Proposed Resolution"
      description: "Optional. If you have a proposal for how to resolve the issue, please describe it clearly."
